jobs:
  main:
    image: node:6
    requires: [~pr, ~commit, ~sd@378:main]
    steps:
      - echo: echo "in trigger-2"
      - touch: touch $SD_ARTIFACTS_DIR/test
  fail:
    image: node:6
    requires: [main]
    steps:
      - fail: fail_me
